  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: my-nginxapp
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: my-nginxapp
    template:
      metadata:
        labels:
          app: my-nginxapp
      spec:
        containers:
        - name: my-nginxapp
          image: nginx
          ports:
          - containerPort: 80
