  apiVersion: v1
  kind: Service
  metadata:
    name: NodePort-service
  spec:
    selector:
      app: my-nginxapp
    type: NodePort  
    ports:
      - port: 80
        targetPort: 80
        nodePort: 30008
